%Navigate to folder containing ephys_tools
s=what('SNLab_ephys');
cd(s.path)

%Initialize Paths 
addpath(genpath(fullfile('preprocessing')),...
    genpath(fullfile('utils')),...
    genpath(fullfile('visualize')),...
    genpath(fullfile('lfp')),...
    genpath(fullfile('io')),...
    genpath(fullfile('behavior')))

if ismember(getenv('USERDOMAIN'), "EPHYS-ANALYSIS-") % Ephys Analyais II
    addpath(what(fullfile('external_packages','Kilosort2Wrapper')).path,...
    genpath('C:\Users\schafferlab\github\neurocode\preProcessing'),...
    genpath('C:\Users\schafferlab\github\kilosort'),...
    genpath('C:\Users\schafferlab\github\neurocode\utilities'),...
    genpath('C:\Users\schafferlab\github\neurocode'),...
    genpath('C:\Users\schafferlab\github\CellExplorer'))
    

elseif ismember(getenv('USERDOMAIN'), "THEHOOK") % Laura's computer
    addpath(what(fullfile('external_packages','Kilosort2Wrapper')).path,...
    genpath('C:\Users\schafferlab\Documents\GitHub\neurocode\preProcessing'),...
    genpath('C:\Users\schafferlab\github\KiloSort'),...
    genpath('C:\Users\schafferlab\Documents\GitHub\neurocode\utilities'),...
    genpath('C:\Users\schafferlab\Documents\GitHub\neurocode'),...
    genpath('C:\Users\schafferlab\Documents\GitHub\CellExplorer'))

end
